name: Revisar señales

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  revisar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install -r requirements.txt
      - run: python main.py
        env:
          8994820850:AAEMSgs4lwT0PEAf9VV8WgaLxZehcBTp9-4: ${{ secrets.TELEGRAM_TOKEN }}
          6420362893: ${{ secrets.TELEGRAM_CHAT_ID }}
